[project]
name = "identity-service-fastapi"
version = "0.1.0"
description = "Identity Service desenvolvido com FastAPI."
authors = [
    {name = "Lucas Oliveira",email = "blesslucas89@gmail.com"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "uvicorn[standard] (>=0.52.0,<0.53.0)",
    "alembic (>=1.18.5,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pre-commit (>=4.6.1,<5.0.0)"
]
